name: Detect Secrets
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  secrets-scan:
    uses: ./.github/workflows/secrets-scanning.yml
    with:
      channel: probely-alerts
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_SECRET }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}