name: Detect Secrets
on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      GITLEAKS_LICENSE:
        required: true
jobs:
  scanSecrets:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [scanSecrets]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c 1-7`" >> $GITHUB_ENV
      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ inputs.channel }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":ALERT: Secrets Detected in GitHub Action. See <https://www.notion.so/snyk/Secret-Leakage-in-GitHub-cfccbb6c78f549fd9a05e978929d6d44|Secret Leakage in GitHub> for the next steps."
                  },
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Ref*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Action URL*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Secrets Scanning>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ env.SHORT_SHA }}>"
                    }
                  ]
                }
              ]
            }